name: Build ExtremeROM for dm3q

on:
  push:
    branches: [ fifteen ]
  pull_request:
    branches: [ fifteen ]
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Free up disk space
      run: |
        sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/hostedtoolcache
        df -h

    - name: Clone ExtremeROM repository
      run: git clone --recurse-submodules https://github.com/osrott61-gh/ExtremeROM.git

    - name: Configure Git identity
      run: |
        git config --global user.email "Github-actions@users.noreply.github.com"
        git config --global user.name "GitHub Actions"
      working-directory: ExtremeROM


    - name: Set up build environment
      run: |
        cd ExtremeROM
        . buildenv.sh dm3q
      timeout-minutes: 30

    - name: Build ROM
      run: |
        cd ExtremeROM
        erom make_rom
      timeout-minutes: 300

    - name: Upload ROM 
      uses: actions/upload-artifact@v4
      with:
        name: ExtremeROM-dm3q
        path: ExtremeROM/out/*.zip
        if-no-files-found: error
        retention-days: 7
      if: success()
